### ISSUE TITLE
Catalina Support?

### ISSUE THREAD

**Issue by brianhubbell** [jonashoechst/Syncthing-BrewBar#6]
Seems this may not work in MacOS Catalina (i think it needs to be _notarized by Apple_). Seeing this error on install:

> “Syncthing BrewBar” can’t be opened because Apple cannot check it for malicious software.

More info: https://support.apple.com/en-us/HT202491

EDIT: it can be run, after selecting open in the above error dialog

**Comment by jonashoechst** [comment]
Thanks for the request. I did a final non-notarized but hardened release, which works using Option-Click -> Open, as described by you. 

Since shell commands are used to start / stop Syncthing, the app itself cannot be sandboxed, and thus not be notarized. With this I decided to stop development and move along with the official [Syncthing for macOS](https://github.com/syncthing/syncthing-macos) application.

Thanks!
